version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: crop-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src/models:/app/src/models
    environment:
      - PYTHONUNBUFFERED=1

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard.Dockerfile
    container_name: crop-dashboard
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000/predict
    volumes:
      - ./data:/app/data
      - ./src/models:/app/src/models
